# Copyright 2017 ParanoidAndroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was automatically generated by vendor/huawei/angler/extract.sh

# An overlay for features that depend on proprietary files
DEVICE_PACKAGE_OVERLAYS := vendor/huawei/angler/overlay

PRODUCT_COPY_FILES += \
    vendor/huawei/angler/proprietary/system/app/HwMMITest/lib/arm64/libManufacture.so:system/app/HwMMITest/lib/arm64/libManufacture.so \
    vendor/huawei/angler/proprietary/system/bin/ssr_setup:system/bin/ssr_setup \
    vendor/huawei/angler/proprietary/system/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/huawei/angler/proprietary/system/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/huawei/angler/proprietary/system/etc/permissions/com.android.omadm.service.xml:system/etc/permissions/com.android.omadm.service.xml \
    vendor/huawei/angler/proprietary/system/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/huawei/angler/proprietary/system/etc/sysconfig/whitelist_com.android.omadm.service.xml:system/etc/sysconfig/whitelist_com.android.omadm.service.xml \
    vendor/huawei/angler/proprietary/system/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/huawei/angler/proprietary/system/lib64/libManufacture.so:system/lib64/libManufacture.so \
    vendor/huawei/angler/proprietary/system/lib/libdmengine.so:system/lib/libdmengine.so \
    vendor/huawei/angler/proprietary/system/lib/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
    vendor/huawei/angler/proprietary/system/lib/soundfx/libfmas.so:system/lib/soundfx/libfmas.so \
    vendor/huawei/angler/proprietary/system/priv-app/DMService/lib/arm/libdmengine.so:system/priv-app/DMService/lib/arm/libdmengine.so \
    vendor/huawei/angler/proprietary/system/priv-app/DMService/lib/arm/libdmjavaplugin.so:system/priv-app/DMService/lib/arm/libdmjavaplugin.so

PRODUCT_PACKAGES += \
    HwMMITest \
    HwSarControlService \
    CarrierServices \
    CNEService \
    ConnMO \
    DCMO \
    DiagMon \
    DMService \
    HiddenMenu \
    HotwordEnrollment \
    qcrilmsgtunnel \
    SprintDM
